name: Upload Empty Room JSON to R2

on:
  schedule:
    # 每天 00:17 UTC 等于北京时间次日 08:17 (UTC+8)
    # 既然设置 0 点和 6 点都不行，我找个有零有整的时间总可以了吧…
    - cron: '17 0 * * *'
  workflow_dispatch: {}

env:
  # Ensures Python uses UTF-8 encoding by default
  PYTHONUTF8: 1

jobs:
  run-uploader:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      USERNAME: ${{ secrets.XJTU_USERNAME }}
      PASSWORD: ${{ secrets.XJTU_PASSWORD }}
      FP_VISITOR_ID: ${{ secrets.FP_VISITOR_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev
          uv pip install boto3

      - name: Run uploader
        run: |
          uv run upload_empty_room.py
